#!/usr/bin/env bash
cd "$(dirname "${BASH_SOURCE[0]}")"

declare IN=${1:-localhost.ext}
declare BASE=$(basename "${IN}" .ext)

mkdir -p out/certs

openssl req -new -nodes -newkey rsa:2048 -keyout "out/certs/${BASE}.key" -out "out/certs/${BASE}.csr" -subj "/C=GB/ST=Oxfordshire/L=Banbury/O=Development-Certificates/CN=${BASE}"
openssl x509 -req -sha256 -days 365 -in "out/certs/${BASE}.csr" -CA out/ca/cert -CAkey out/ca/key -CAcreateserial -extfile "${IN}" -out "out/certs/${BASE}.crt"

